name: Preprocessing Workflow

on:
  push:
    branches:
      - main

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          pip install pandas
          pip install scikit-learn

      - name: Download Dataset
        run: |
          echo "Dataset diunduh manual dari Kaggle"

      - name: Run Preprocessing
        run: |
          python preprocessing/automate_RatnaSyifa.py
